### PR TITLE
Feature YouTube layout and customization

### PR DESCRIPTION
**Pull request by rubenpazch**
We did work on Project number 1 from HTML & CSS  about making a clone of the youtube page, we did use HTML & CSS for facing this project and flexbox model in most of the layouts.

### CODE REVIEW

**Comment by rubenpazch** [comment]
We did work on the README file and also make changes as a result of HMTL & CSS validation, we fix bugs and follow all recommendations from the pathwright.

**Comment by shshamim63** [comment]
## Status :red_circle: [Changes Required] :red_circle: 
___
Hi @rubenpazch  and @enelesmai :wave: ,
Awesome initiative :clap: , Project contains a descriptive readme. code looks neat and clean(except some indentation problem). Contains all the part that is required to decorate the page. But one simple issue is blocking me to approve this project.
___
#### Please follow the instruction below to complete the project.
___
### :spades: [Mandatory Changes] :spades: 
___
1. You were asked to check HTML markup with this validator https://validator.w3.org/#validate_by_upload.
I did that and found one error. Please resolve that.
image
___ 
### :clubs: [Optional Changes] :clubs: 
___
1. As you have enabled stickler on this repository. Lets configure it properly. Please follow the instructions on this [link](https://github.com/microverseinc/linters-config/tree/master/css) step by step. And you will be done with it.
___
#### please resolve the mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/)

**Comment by rOluochKe** [comment]
@enelesmai and @rubenpazch Good Job on this project, you executed it well. Although fix the linting errors.

- When that is done, resubmit for review.
- If you are having a challenge, you can ask for assistance @rOluochKe

**Comment by enelesmai** [comment]
Stickler validations were fixed, all checks have passed now

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Hi Team,
## Great  work, Congratulation :+1: 
You did all changes required previously. Go ahead and merge to master
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
